# Generated by Django 5.2.2 on 2025-06-06 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('role', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('franchise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='franchise.franchise')),
            ],
        ),
    ]
