# Generated by Django 5.2.2 on 2025-06-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char', '0001_initial'),
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='franchise.franchise'),
        ),
    ]
